
spring:
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/jandb
    driver-class-name: org.mariadb.jdbc.Driver
    username: ENC(AOlqjc7Vu97CirlATUxSDg==)
    password: ENC(qg5r8Eg7+MunDRuXG0nfcg==)
#url: jdbc:mariadb://127.0.0.1:3306/jandb
logging:
  config: classpath:log/logback-spring.xml

eureka:
  instance:
    prefer-ip-address: true
  client:
    registryFetchIntervalSeconds: 5
    disable-delta: true
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://192.168.56.1:8761/eureka
      #defaultZone: http://localhost:8761/eureka

cust.security:
  ignore:
    path:
      - /favicon.ico
      - /error
    resource:
      - exe

encrypt:
  algolithm: PBEWithMD5AndDES
  key-obtention-iterations: 1000
  pool-size: 1
  salt-generator-class-name: org.jasypt.salt.RandomSaltGenerator
  string-output-type: base64